package model;
// Generated 18/11/2018 08:20:16 AM by Hibernate Tools 4.3.1



/**
 * AmigosId generated by hbm2java
 */
public class AmigosId  implements java.io.Serializable {


     private String correoUsuario;
     private String correoAmigo;

    public AmigosId() {
    }

    public AmigosId(String correoUsuario, String correoAmigo) {
       this.correoUsuario = correoUsuario;
       this.correoAmigo = correoAmigo;
    }
   
    public String getCorreoUsuario() {
        return this.correoUsuario;
    }
    
    public void setCorreoUsuario(String correoUsuario) {
        this.correoUsuario = correoUsuario;
    }
    public String getCorreoAmigo() {
        return this.correoAmigo;
    }
    
    public void setCorreoAmigo(String correoAmigo) {
        this.correoAmigo = correoAmigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmigosId) ) return false;
		 AmigosId castOther = ( AmigosId ) other; 
         
		 return ( (this.getCorreoUsuario()==castOther.getCorreoUsuario()) || ( this.getCorreoUsuario()!=null && castOther.getCorreoUsuario()!=null && this.getCorreoUsuario().equals(castOther.getCorreoUsuario()) ) )
 && ( (this.getCorreoAmigo()==castOther.getCorreoAmigo()) || ( this.getCorreoAmigo()!=null && castOther.getCorreoAmigo()!=null && this.getCorreoAmigo().equals(castOther.getCorreoAmigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCorreoUsuario() == null ? 0 : this.getCorreoUsuario().hashCode() );
         result = 37 * result + ( getCorreoAmigo() == null ? 0 : this.getCorreoAmigo().hashCode() );
         return result;
   }   


}


