package model;
// Generated 28/11/2018 09:02:11 AM by Hibernate Tools 4.3.1



/**
 * Amigos generated by hbm2java
 */
public class Amigos  implements java.io.Serializable {


     private AmigosId id;
     private Usuario usuarioByCorreoAmigo;
     private Usuario usuarioByCorreoUsuario;

    public Amigos() {
    }

	
    public Amigos(AmigosId id) {
        this.id = id;
    }
    public Amigos(AmigosId id, Usuario usuarioByCorreoAmigo, Usuario usuarioByCorreoUsuario) {
       this.id = id;
       this.usuarioByCorreoAmigo = usuarioByCorreoAmigo;
       this.usuarioByCorreoUsuario = usuarioByCorreoUsuario;
    }
   
    public AmigosId getId() {
        return this.id;
    }
    
    public void setId(AmigosId id) {
        this.id = id;
    }
    public Usuario getUsuarioByCorreoAmigo() {
        return this.usuarioByCorreoAmigo;
    }
    
    public void setUsuarioByCorreoAmigo(Usuario usuarioByCorreoAmigo) {
        this.usuarioByCorreoAmigo = usuarioByCorreoAmigo;
    }
    public Usuario getUsuarioByCorreoUsuario() {
        return this.usuarioByCorreoUsuario;
    }
    
    public void setUsuarioByCorreoUsuario(Usuario usuarioByCorreoUsuario) {
        this.usuarioByCorreoUsuario = usuarioByCorreoUsuario;
    }




}


