package model;
// Generated 18/11/2018 08:20:16 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Intercambio generated by hbm2java
 */
public class Intercambio  implements java.io.Serializable {


     private Integer id;
     private Tema tema;
     private String nombre;
     private BigDecimal montoMaximo;
     private Date fechaLimite;
     private Date fechaIntercambio;
     private String comentarios;
     private Set usuarioIntercambios = new HashSet(0);

    public Intercambio() {
    }

    public Intercambio(Tema tema, String nombre, BigDecimal montoMaximo, Date fechaLimite, Date fechaIntercambio, String comentarios, Set usuarioIntercambios) {
       this.tema = tema;
       this.nombre = nombre;
       this.montoMaximo = montoMaximo;
       this.fechaLimite = fechaLimite;
       this.fechaIntercambio = fechaIntercambio;
       this.comentarios = comentarios;
       this.usuarioIntercambios = usuarioIntercambios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getMontoMaximo() {
        return this.montoMaximo;
    }
    
    public void setMontoMaximo(BigDecimal montoMaximo) {
        this.montoMaximo = montoMaximo;
    }
    public Date getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(Date fechaLimite) {
        this.fechaLimite = fechaLimite;
    }
    public Date getFechaIntercambio() {
        return this.fechaIntercambio;
    }
    
    public void setFechaIntercambio(Date fechaIntercambio) {
        this.fechaIntercambio = fechaIntercambio;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Set getUsuarioIntercambios() {
        return this.usuarioIntercambios;
    }
    
    public void setUsuarioIntercambios(Set usuarioIntercambios) {
        this.usuarioIntercambios = usuarioIntercambios;
    }




}


