package model;
// Generated 28/11/2018 09:02:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String correo;
     private String nombre;
     private String alias;
     private String contrasenia;
     private Boolean registrado;
     private Set amigosesForCorreoAmigo = new HashSet(0);
     private Set amigosesForCorreoUsuario = new HashSet(0);
     private Set usuarioIntercambios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String correo) {
        this.correo = correo;
    }
    public Usuario(String correo, String nombre, String alias, String contrasenia, Boolean registrado, Set amigosesForCorreoAmigo, Set amigosesForCorreoUsuario, Set usuarioIntercambios) {
       this.correo = correo;
       this.nombre = nombre;
       this.alias = alias;
       this.contrasenia = contrasenia;
       this.registrado = registrado;
       this.amigosesForCorreoAmigo = amigosesForCorreoAmigo;
       this.amigosesForCorreoUsuario = amigosesForCorreoUsuario;
       this.usuarioIntercambios = usuarioIntercambios;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Boolean getRegistrado() {
        return this.registrado;
    }
    
    public void setRegistrado(Boolean registrado) {
        this.registrado = registrado;
    }
    public Set getAmigosesForCorreoAmigo() {
        return this.amigosesForCorreoAmigo;
    }
    
    public void setAmigosesForCorreoAmigo(Set amigosesForCorreoAmigo) {
        this.amigosesForCorreoAmigo = amigosesForCorreoAmigo;
    }
    public Set getAmigosesForCorreoUsuario() {
        return this.amigosesForCorreoUsuario;
    }
    
    public void setAmigosesForCorreoUsuario(Set amigosesForCorreoUsuario) {
        this.amigosesForCorreoUsuario = amigosesForCorreoUsuario;
    }
    public Set getUsuarioIntercambios() {
        return this.usuarioIntercambios;
    }
    
    public void setUsuarioIntercambios(Set usuarioIntercambios) {
        this.usuarioIntercambios = usuarioIntercambios;
    }




}


